dist: xenial   # required for Python >= 3.7

sudo: false

language: python

services:
  - docker

cache: pip

python:
  - "3.6"
  - "3.7"

before_script:
  - sleep 15
  - docker run -d --name some-rabbit -p 5672:5672 -p 15672:15672 rabbitmq:3-management
  - sleep 15

install:
  - make deps

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)